-- create table todos
CREATE TABLE todos (
	id INT AUTO_INCREMENT,
	user_id INT NOT NULL DEFAULT 0,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	status SET('0', '1', '2') NOT NULL DEFAULT '0',
	priority SET('0', '1', '2') NOT NULL DEFAULT '0',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL,
	deadline TIMESTAMP NULL DEFAULT NULL,
	done boolean NOT NULL DEFAULT false,
	PRIMARY KEY (id)
);